language: python
python:
  - "2.7"
branches:
  only:
    - master
install:
  - source .travis_install.sh
  - source .travis_ssh_setup.sh
  - python -c 'from pwn import *; print pwnlib.term.term_mode' NOTERM
  - python -c 'from pwn import *; print pwnlib.term.term_mode' NOTERM
  - python -c 'from pwn import *; print pwnlib.term.term_mode' NOTERM
  - python -c 'from pwn import *; print pwnlib.term.term_mode' NOTERM

script: make -C docs doctest
