language: python
python:
  - "2.7"
branches:
  only:
    - master
install:
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository --yes ppa:pwntools/binutils
  - sudo apt-get update
  - sudo apt-get install binutils-arm-linux-gnu binutils-mips-linux-gnu
  - wget -nc http://www.capstone-engine.org/download/2.1.2/capstone-2.1.2_amd64.deb
  - sudo dpkg -i *.deb
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - pip install .
script: make -C docs doctest
